import { ParameterType } from 'typedoc';
import { DEFAULT_SIDEBAR_OPTIONS } from '../options.js';

/**
 *
 * If TypeDoc is run from outside of the sveltepress project root directory, then `docsRoot` should be set to the path of the sveltepress root directory.
 *
 * e.g. the following file structure:
 *
 * ```
 *   ├── package.json
 *   ├── typedoc.json
 *   └── docs/
 *       └── .sveltepress/
 *       └── typedoc-api/
 *           └── index.md
 * ```
 *
 * Requires the following config:
 *
 * ```json filename="typedoc.json"
 * {
 *    "out": "./docs/typedoc-api",
 *    "docsRoot": "./docs",
 * }
 * ```
 */
export const docsRoot = {
  help: 'The path to the sveltepress project root.',
  type: ParameterType.Path,
  defaultValue: './',
};

/**
 * **sidebar.autoConfiguration**
 *
 * Set to `false` to disable sidebar generation. Defaults to true.
 *
 * **sidebar.collapsible**
 *
 * Determines if sidebar items with children are open or closed. Set `collapsible` to `false` to set sidebar items as open by default.
 *
 * **sidebar.pretty**
 *
 * Pretty format the sidebar JSON.
 *
 */
export const sidebar = {
  help: 'Configures the autogenerated sveltepress sidebar.',
  type: ParameterType.Mixed,
  defaultValue: DEFAULT_SIDEBAR_OPTIONS,
};
