/*
 * THIS FILE IS AUTO GENERATED FROM THE OPTIONS CONFIG. DO NOT EDIT DIRECTLY
 */

/**
 * Describes the options declared by the plugin.
 */
export interface PluginOptions {
  /**
   * The path to the sveltepress project root.
   */
  docsRoot?: string;

  /**
   * Configures the autogenerated sveltepress sidebar.
   */
  sidebar?: Sidebar;
}

export interface Sidebar {
  autoConfiguration: boolean;
  pretty: boolean;
  collapsible: boolean;
}
